<a href="https://colab.research.google.com/github/GauravGupta7/project_S/blob/master/FCC_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Torch Library:

In [1]:
import torch

Creating a tensor having value 4.0 stored in it

In [2]:
#tensor containing a number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
#tensor containing a Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [4]:
#tensor containing a Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [5]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Getting the shapes of tensors:

In [6]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


Creating tensors using arithmetic operations

In [8]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

# Arithmetic operations.
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

Creating torch arrays from NUMPY

In [10]:
import numpy as np
x = np.array([[1, 2], [3, 4.]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

x.dtype, y.dtype

(dtype('float64'), torch.float64)

From torch to numpy


In [11]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])