<a href="https://colab.research.google.com/github/GauravGupta7/project_S/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is the code as taught in : https://www.youtube.com/watch?v=8Y0qQEh7dJg

In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

**ARRAYS IN NUMPY**

In [2]:
#creating a single dimensional numpy array from python list:
list1 = [1,2,3,4,5]
np_array1 = np.array(list1, dtype = np.int8)
np_array1

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
#creating a multi dimensional numpy array from multi dimensional python list:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
np_array2 = np.array(list2, dtype = np.int8)
np_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [4]:
#creating a numpy array in a range:
array1 = np.arange(1, 10)
print(array1)

#creating a numpy array in a range with 2 steps:
array2 = np.arange(1, 10, 2)
print(array2)

#use of linspace:
array3 = np.linspace(0, 5, 5)
print(array3)

#using the random function:
array4 = np.random.randint(10, 50, size=(2,3))
print(array4)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.   1.25 2.5  3.75 5.  ]
[[38 49 45]
 [39 41 11]]


**SLICING & INDEXING OF NUMPY ARRAYS**


In [5]:
#Changing the value at a particular index:
print("np_array2:\n", np_array2)
np_array2[0, 0] = 2
print(np_array2)

np_array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#another technique for the above:
np_array2.itemset((0, 2), 2)
print(np_array2)

[[2 2 2]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np_array2[0,1])
print(np_array2[0])
print(np_array2.item(0,1))
print(np_array2.item(4))

2
[2 2 2]
2
5


In [8]:
print("np_array2\n", np_array2)
a = np.take(np_array2, [0, 3, 6])
print(a)

np_array2
 [[2 2 2]
 [4 5 6]
 [7 8 9]]
[2 4 7]


In [9]:
#to update multiple values at once:
print("np_array2\n", np_array2)
np.put(np_array2, [1, 4, 7], [10, 10 ,10])
print("np_array2\n", np_array2)

np_array2
 [[2 2 2]
 [4 5 6]
 [7 8 9]]
np_array2
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]


In [10]:
#to get one column(for example, here we print second column of np_array2):
print("np_array2:\n", np_array2)
print("Second column of np_array2:\n", np_array2[:, 1])

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
Second column of np_array2:
 [10 10 10]


In [11]:
#to get one row(for example, here we try to get the third row of np_array2):
print("np_array2:\n", np_array2)
print("Third row of np_array2:\n", np_array2[2, :])

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
Third row of np_array2:
 [ 7 10  9]


In [12]:
#to print the np_array2 upside down (Water Image):
print("np_array2:\n", np_array2)
print("-------------\n", np_array2[::-1])

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
-------------
 [[ 7 10  9]
 [ 4 10  6]
 [ 2 10  2]]


In [13]:
#to print only the even element of the array:
print("np_array2:\n", np_array2)
print("-------------\n")
evens = np_array2[np_array2 % 2 == 0]
print("The even elements of the array are:", evens)

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
-------------

The even elements of the array are: [ 2 10  2  4 10  6 10]


In [14]:
#to print elements of the array using certain conditions:
print("np_array2:\n", np_array2)
cond1 = np_array2[np_array2 > 5]
print("Elements of the array greater than 5 are: ", cond1)
cond2 = np_array2[(np_array2 > 5) & (np_array2 < 9)]
print("Elements of the array greater than 5 and less than 9 are:", cond2)

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
Elements of the array greater than 5 are:  [10 10  6  7 10  9]
Elements of the array greater than 5 and less than 9 are: [6 7]


In [15]:
#to get the unique elements of numpy array:
print("np_array2:\n", np_array2)
u_elements = np.unique(np_array2)
print("The elemnts in the np_array2 are:\n", u_elements)

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
The elemnts in the np_array2 are:
 [ 2  4  6  7  9 10]


**RESHAPING NUMPY ARRAYS**

In [17]:
#The reshape() function
print("np_array2:\n", np_array2)
np_array2.reshape((1, 9))
print("The reshaped array is:", np_array2.reshape((1, 9)))

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
The reshaped array is: [[ 2 10  2  4 10  6  7 10  9]]


In [20]:
#The resize function:
print("np_array2:\n", np_array2)
print("The resized array is:\n", np.resize(np_array2, (2, 5)))

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
The resized array is:
 [[ 2 10  2  4 10]
 [ 6  7 10  9  2]]


In [23]:
#Transpose of an array:
print("np_array2:\n", np_array2)
print("The transpose of the array is:\n", np_array2.transpose())

#The swapaxes() functiom:
print("np_array2:\n", np_array2)
print("After swapping axes:\n", np_array2.swapaxes(0,1))

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
The transpose of the array is:
 [[ 2  4  7]
 [10 10 10]
 [ 2  6  9]]
np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
After swapping axes:
 [[ 2  4  7]
 [10 10 10]
 [ 2  6  9]]


In [28]:
#The flatten() function:
print("np_array2:\n", np_array2)
print("The flattened array is:\n", np_array2.flatten())

print("np_array2:\n", np_array2)
print("Flattened at column:\n", np_array2.flatten('F'))

np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
The flattened array is:
 [ 2 10  2  4 10  6  7 10  9]
np_array2:
 [[ 2 10  2]
 [ 4 10  6]
 [ 7 10  9]]
Flattened at column:
 [ 2  4  7 10 10 10  2  6  9]


In [34]:
#Sorting:
print("np_array2:\n", np_array2)
print("Sorted Row wise:\n", np.sort(np_array2, axis=0))

print("np_array2:\n", np_array2)
print("Sorted Column wise:\n", np.sort(np_array2, axis=1))

np_array2:
 [[ 2  2 10]
 [ 4  6 10]
 [ 7  9 10]]
Sorted Row wise:
 [[ 2  2 10]
 [ 4  6 10]
 [ 7  9 10]]
np_array2:
 [[ 2  2 10]
 [ 4  6 10]
 [ 7  9 10]]
Sorted Column wise:
 [[ 2  2 10]
 [ 4  6 10]
 [ 7  9 10]]


**STACKING AND SPLITTING ARRAYS**